-- Efecto sync schema.
--
-- Run this once in the Supabase SQL editor (Dashboard -> SQL Editor -> New
-- query -> paste -> Run). It is idempotent, so re-running it is harmless.
--
-- One generic table holds every kind of record as JSON rather than five tables
-- mirroring the Dexie stores. Adding a field to a Lesson or a Todo then needs
-- no migration here at all -- the app owns the shape, this owns the transport.

create table if not exists public.records (
  user_id    uuid    not null references auth.users on delete cascade,
  -- which Dexie store the row belongs to: routines | entries | lessons |
  -- todoFolders | todos
  kind       text    not null,
  -- the record's local id, generated by the client (crypto.randomUUID, or
  -- "routineId|date" for an entry) and identical on every device
  id         text    not null,
  -- the whole record; null once deleted
  data       jsonb,
  deleted    boolean not null default false,
  -- the client's own stamp, in epoch ms. Conflict resolution only: the later
  -- write wins.
  updated_at bigint  not null,
  -- server time, set on every write. The pull cursor, and deliberately NOT the
  -- client stamp: a device whose clock runs slow would otherwise push rows
  -- that another device's cursor has already scrolled past, and they would
  -- never be seen again.
  synced_at  timestamptz not null default now(),
  primary key (user_id, kind, id)
);

-- Pull is always "everything of mine since a cursor", so that is the index.
create index if not exists records_pull_idx on public.records (user_id, synced_at);

-- Keep synced_at honest on updates; the default only covers inserts.
create or replace function public.touch_synced_at() returns trigger as $$
begin
  new.synced_at := now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists records_touch_synced_at on public.records;
create trigger records_touch_synced_at
  before insert or update on public.records
  for each row execute function public.touch_synced_at();

-- Row level security: a user can only ever see and write their own rows.
alter table public.records enable row level security;

drop policy if exists "own records" on public.records;
create policy "own records" on public.records
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Realtime: let the server tell a signed-in device that another one wrote,
-- instead of every device asking on a timer. `postgres_changes` honours the
-- policy above, so a client is only ever told about its own rows -- and the
-- app still pulls through the ordinary cursor afterwards, treating the event
-- as a nudge rather than as data.
do $$
begin
  alter publication supabase_realtime add table public.records;
exception
  when duplicate_object then null;  -- already published; re-running is harmless
end
$$;

-- A delete arrives with nothing but its key unless the whole old row is
-- replicated, and the key is what the nudge needs.
alter table public.records replica identity full;
